In [125]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [126]:
df = pd.read_csv('almaty_centers_and_hospitals_reviews.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23661 entries, 0 to 23660
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   id             23661 non-null  int64
 1   name           23661 non-null  object
 2   category       23661 non-null  object
 3   city           23661 non-null  object
 4   district       23661 non-null  object
 5   latitude       23661 non-null  float64
 6   longitude      23661 non-null  float64
 7   rating         23661 non-null  float64
 8   review_count   23661 non-null  int64
 9   work_hours     23661 non-null  object
 10  address        23661 non-null  object
 11  tags           23661 non-null  object
 12  office_id      23661 non-null  int64
 13  review_text    23661 non-null  object
 14  review_rating  23661 non-null  float64
 15  review_date    0 non-null      float64
dtypes: float64(5), int64(3), object(8)
memory usage: 2.9+ MB

In [127]:
df.describe()

,id,latitude,longitude,rating,review_count,office_id,review_rating,review_date
count,2.366100e+04,23661.000000,23661.000000,23661.000000,23661.000000,2.366100e+04,23661.000000,0.0
mean,2.380384e+16,43.256310,76.890699,3.779447,1441.309328,2.380384e+16,3.035544,NaN
std,2.576911e+16,0.044245,0.056224,0.554513,636.800394,2.576911e+16,1.902162,NaN
min,9.429940e+15,43.206951,76.790634,2.600000,475.000000,9.429940e+15,1.000000,NaN
25%,9.429940e+15,43.228526,76.838086,3.500000,916.000000,9.429940e+15,1.000000,NaN
50%,9.429940e+15,43.233299,76.900985,3.800000,1403.000000,9.429940e+15,3.000000,NaN
75%,9.429940e+15,43.307362,76.932978,4.100000,1691.000000,9.429940e+15,5.000000,NaN
max,7.000000e+16,43.365744,77.013877,4.700000,2880.000000,7.000000e+16,5.000000,NaN

In [128]:
df.columns

Index(['id', 'name', 'category', 'city', 'district', 'latitude', 'longitude',
       'rating', 'review_count', 'work_hours', 'address', 'tags', 'office_id',
       'review_text', 'review_rating', 'review_date'],
      dtype='object')

In [129]:
df.shape

(23661, 16)

In [130]:
df.head()

,id,name,category,city,district,latitude,longitude,rating,review_count,work_hours,address,tags,office_id,review_text,review_rating,review_date
0,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,Бардак. Номер қателесіп беріп жіберген. Өзің б...,1.0,NaN
1,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,Здраствуйте хочу рассказать о случае в котором...,1.0,NaN
2,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,"Нервные сотрудники, 5 часов ожиданий в пустую,...",1.0,NaN
3,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,Здрово!,4.0,NaN
4,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,Барлығы өз ісінің маманы,5.0,NaN

In [131]:
df['id'].value_counts()

id
9429940001088063     2856
9429940000802042     1744
70000001038775734    1670
9429940000884972     1614
9429940000802044     1448
70000001038896362    1425
9429940000802108     1398
9429940000794523     1340
9429940000794524     1302
9429940000838334     1276
9429940000802043     1056
9429940000794522      918
9429940000794876      886
9429940000794521      884
70000001065029885     878
9429940000794875      688
9429940000802040      636
70000001035295134     597
70000001029034925     576
70000001075843105     469
Name: count, dtype: int64

In [132]:
df.drop(columns=['review_date'], inplace=True)

df['review_rating'].fillna(df['review_rating'].mean(), inplace=True)

df['work_hours'].fillna('No Data', inplace=True)

df['rating'] = df['rating'].clip(lower=1, upper=5)
df['review_rating'] = df['review_rating'].clip(lower=1, upper=5)

df['review_text'] = df['review_text'].str.replace(r'[^a-zA-Zа-яА-ЯёЁіІңҢәӘөӨұҰқҚғҒүҮұҰ\s]', '', regex=True)
df['review_text'] = df['review_text'].str.lower()
df['review_text'].replace(r'^\s*$', 'No Review', regex=True, inplace=True)
df = df[~df['review_text'].str.isnumeric()]

df.drop_duplicates(subset=['id', 'review_text'], keep='first', inplace=True)

In [133]:
missing_data = df.isnull().sum()
print("Missing Data After Cleaning:\n", missing_data)

print("Cleaned Data Shape:", df.shape)
print("Cleaned Data Columns:", df.columns)

df.head()

Missing Data After Cleaning:
 id               0
name             0
category         0
city             0
district         0
latitude         0
longitude        0
rating           0
review_count     0
work_hours       0
address          0
tags             0
office_id        0
review_text      0
review_rating    0
dtype: int64
Cleaned Data Shape: (23465, 15)
Cleaned Data Columns: Index(['id', 'name', 'category', 'city', 'district', 'latitude', 'longitude',
       'rating', 'review_count', 'work_hours', 'address', 'tags', 'office_id',
       'review_text', 'review_rating'],
      dtype='object')

,id,name,category,city,district,latitude,longitude,rating,review_count,work_hours,address,tags,office_id,review_text,review_rating
0,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,бардак номер қателесіп беріп жіберген өзің бар...,1.0
1,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здраствуйте хочу рассказать о случае в котором...,1.0
2,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,нервные сотрудники часов ожиданий в пустую не...,1.0
3,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здрово,4.0
4,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,барлығы өз ісінің маманы,5.0

In [134]:
print(df['review_text'].head())

0    бардак номер қателесіп беріп жіберген өзің бар...
1    здраствуйте хочу рассказать о случае в котором...
2    нервные сотрудники  часов ожиданий в пустую не...
3                                               здрово
4                             барлығы өз ісінің маманы
Name: review_text, dtype: object

In [135]:
df['review_text'].replace(r'^\s*$', 'No Review', regex=True, inplace=True)
df['review_rating'] = df['review_rating'].clip(lower=1, upper=5)
df.drop_duplicates(subset=['office_id', 'review_text'], keep='first', inplace=True)

In [136]:
print(df['review_text'].head())

0    бардак номер қателесіп беріп жіберген өзің бар...
1    здраствуйте хочу рассказать о случае в котором...
2    нервные сотрудники  часов ожиданий в пустую не...
3                                               здрово
4                             барлығы өз ісінің маманы
Name: review_text, dtype: object

In [137]:
missing_data = df.isnull().sum()
print("Missing Data After Cleaning:\n", missing_data)

print("Cleaned Data Shape:", df.shape)
print("Cleaned Data Columns:", df.columns)

df.head()

Missing Data After Cleaning:
 id               0
name             0
category         0
city             0
district         0
latitude         0
longitude        0
rating           0
review_count     0
work_hours       0
address          0
tags             0
office_id        0
review_text      0
review_rating    0
dtype: int64
Cleaned Data Shape: (23465, 15)
Cleaned Data Columns: Index(['id', 'name', 'category', 'city', 'district', 'latitude', 'longitude',
       'rating', 'review_count', 'work_hours', 'address', 'tags', 'office_id',
       'review_text', 'review_rating'],
      dtype='object')

,id,name,category,city,district,latitude,longitude,rating,review_count,work_hours,address,tags,office_id,review_text,review_rating
0,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,бардак номер қателесіп беріп жіберген өзің бар...,1.0
1,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здраствуйте хочу рассказать о случае в котором...,1.0
2,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,нервные сотрудники часов ожиданий в пустую не...,1.0
3,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здрово,4.0
4,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,барлығы өз ісінің маманы,5.0

In [138]:
df['category'].value_counts()

category
ЦОН         12346
Больница    11119
Name: count, dtype: int64

In [139]:
df['tags'].value_counts()

tags
ЦОН                                                                                                                                                                                                                                                                                                                                                                               12346
Больницы                                                                                                                                                                                                                                                                                                                                                                           8978
Многопрофильные медицинские центры, Медицинские анализы, Медицинская диагностика, Детские врачи, Кардиолог, Ведение беременности, Больницы, Процедурный кабинет, Невролог, Терапевт, Уролог, Гинеколог, ЛОР (отоларинголог), Эндокринолог, Хирург, Маммолог, Офтальмолог, Ревматолог, Аллерголог-иммунолог, Гастроэнтеролог, Нефролог, Онколог                                     1265
Многопрофильные медицинские центры, Медицинская диагностика, Детские врачи, Медицинские анализы, Гинеколог, Уролог, Дерматолог, ЛОР (отоларинголог), Офтальмолог, Кардиолог, Проктолог, Эндокринолог, Хирург, Пульмонолог, Медицинские комиссии, Аллерголог-иммунолог, Ревматолог, Травматолог-ортопед, Больницы, Логопед, Онколог, Терапевт, Флеболог, Маммолог, Инфекционист      876
Name: count, dtype: int64

In [140]:
# import ast
#
# def extract_work_hours_features(work_hours_str):
#     try:
#         work_hours_data = ast.literal_eval(work_hours_str)
#
#         work_day_count = 0
#         work_time_count_per_day = 0
#
#         for day, data in work_hours_data.items():
#             if 'working_hours' in data and len(data['working_hours']) > 0:
#                 work_day_count += 1
#                 for hours in data['working_hours']:
#                     start_time = hours['from']
#                     end_time = hours['to']
#                     start_hour = int(start_time.split(':')[0])
#                     end_hour = int(end_time.split(':')[0])
#                     work_time_count_per_day = (end_hour - start_hour)
#
#         work_time_count_per_week = work_time_count_per_day * work_day_count
#
#         return work_day_count, work_time_count_per_day, work_time_count_per_week
#     except (ValueError, TypeError, KeyError) as e:
#         return 0, 0, 0
#
# df[['work_day_count', 'work_time_count_per_day', 'work_time_count_per_week']] = df['work_hours'].apply(
#     lambda x: pd.Series(extract_work_hours_features(str(x)))
# )
#
# print(df[['work_day_count', 'work_time_count_per_day', 'work_time_count_per_week']].head())

In [141]:
import ast

def extract_work_hours_features(work_hours_str):
    try:
        work_hours_data = ast.literal_eval(work_hours_str)

        work_day_count = 0
        work_time_count_per_day = 0

        for day, data in work_hours_data.items():
            if 'working_hours' in data and len(data['working_hours']) > 0:
                for hours in data['working_hours']:
                    start_time = hours['from']
                    end_time = hours['to']

                    if start_time == '09:00' and end_time == '22:00':
                        work_time_count_per_day = 13
                        work_day_count += 1
                    else:
                        start_hour = int(start_time.split(':')[0])
                        end_hour = int(end_time.split(':')[0])
                        work_time_count_per_day = (end_hour - start_hour)
                        work_day_count += 1

        if work_day_count == 0:
            work_day_count = 7
            work_time_count_per_day = 24

        return work_day_count, work_time_count_per_day
    except (ValueError, TypeError, KeyError) as e:
        return 7, 24

df[['work_day_count', 'work_time_count_per_day']] = df['work_hours'].apply(
    lambda x: pd.Series(extract_work_hours_features(str(x)))
)

print(df[['work_day_count', 'work_time_count_per_day']].head())

   work_day_count  work_time_count_per_day
0               5                        9
1               5                        9
2               5                        9
3               5                        9
4               5                        9

In [142]:
print(df['work_hours'].head())

0    {'Fri': {'working_hours': [{'from': '09:00', '...
1    {'Fri': {'working_hours': [{'from': '09:00', '...
2    {'Fri': {'working_hours': [{'from': '09:00', '...
3    {'Fri': {'working_hours': [{'from': '09:00', '...
4    {'Fri': {'working_hours': [{'from': '09:00', '...
Name: work_hours, dtype: object

In [143]:
print(df['work_time_count_per_day'].value_counts())
print(df['work_day_count'].value_counts())

work_time_count_per_day
9     13574
11     3692
24     3174
12     1265
8       884
13      876
Name: count, dtype: int64
work_day_count
5    14458
7     5315
6     3692
Name: count, dtype: int64

In [144]:
missing_data = df.isnull().sum()
print("Missing Data After Cleaning:\n", missing_data)

print("Cleaned Data Shape:", df.shape)
print("Cleaned Data Columns:", df.columns)

df.head()

Missing Data After Cleaning:
 id                         0
name                       0
category                   0
city                       0
district                   0
latitude                   0
longitude                  0
rating                     0
review_count               0
work_hours                 0
address                    0
tags                       0
office_id                  0
review_text                0
review_rating              0
work_day_count             0
work_time_count_per_day    0
dtype: int64
Cleaned Data Shape: (23465, 17)
Cleaned Data Columns: Index(['id', 'name', 'category', 'city', 'district', 'latitude', 'longitude',
       'rating', 'review_count', 'work_hours', 'address', 'tags', 'office_id',
       'review_text', 'review_rating', 'work_day_count',
       'work_time_count_per_day'],
      dtype='object')

,id,name,category,city,district,latitude,longitude,rating,review_count,work_hours,address,tags,office_id,review_text,review_rating,work_day_count,work_time_count_per_day
0,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,бардак номер қателесіп беріп жіберген өзің бар...,1.0,5,9
1,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здраствуйте хочу рассказать о случае в котором...,1.0,5,9
2,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,нервные сотрудники часов ожиданий в пустую не...,1.0,5,9
3,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,здрово,4.0,5,9
4,9429940001088063,Специализированный центр обслуживания населени...,ЦОН,Алматы,улица Ак-Кайнар,43.308773,76.838086,3.6,2880,"{'Fri': {'working_hours': [{'from': '09:00', '...","улица Ак-Кайнар, 1",ЦОН,9429940001088063,барлығы өз ісінің маманы,5.0,5,9

In [145]:
df.to_csv('almaty_psc_hospital_wrangled.csv', index=False)

In [147]:
filtered_data = df[df['work_time_count_per_day'] == 5]
print(filtered_data[['name', 'work_day_count', 'work_time_count_per_day', 'rating', 'review_text']].head())

Empty DataFrame
Columns: [name, work_day_count, work_time_count_per_day, rating, review_text]
Index: []

In [148]:
filtered_data = df[df['work_day_count'] == 7]
filtered_data[['work_hours']].head()

                                              work_hours
14793  {'Fri': {'working_hours': [{'from': '00:00', '...
14794  {'Fri': {'working_hours': [{'from': '00:00', '...
14795  {'Fri': {'working_hours': [{'from': '00:00', '...
14796  {'Fri': {'working_hours': [{'from': '00:00', '...
14797  {'Fri': {'working_hours': [{'from': '00:00', '...